#!/bin/bash


#Colores para mensajes
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[0;35m"
green="\033[1;32m"
yellow="\033[1;33m"
Purple"\033[0;35m"
Cyan="\033[0;36"
Cafe="\033[0;35m"
Fiuscha="\033[0;35m"
blue="\033[1;34m"


nombre;
apellido;

#OPCIONES DEL MENU
a="Cual es tu nombre?"
b="Cual es tu apellido?"
c="Cual es tu edad?"
d="Salir del programa"




clear
echo -e "$red Este es mi primer programa en bash"
sleep 3
echo -e "$green Este programa sera aleatorio para youtube"
sleep 3
echo -e "$blue Crearemos un menu de opciones"
sleep 3
echo
echo

PS3= "Selecciona una opcion: "

function menu_principal(){

select menu in "$a" "$b" $c" "$d";
do
case $menu in
$a)
echo -e " "$purple(*)$blue Ingresa tu nombre:$green "
read nombre
echo -e " "$purple(*)$blue Tu nombre es:$green $nombre "
sleep 2
echo -e "$blue Volviendo al menu principal"
menu_principal
;;
$b)
echo -e " "$purple(*)$blue Ingresa tu apellido:$green "
read nombre
echo -e " "$purple(*)$blue Tu apellido es:$green $apellido "
sleep 2
echo -e "$blue Volviendo al menu principal" 
menu_principal
;;
$c)

echo -e "$purple(*)$blue Ingresa tu edad:$green "
read edad
echo -e "$purple(*)$blue tu edad es de: $green $edad $blue años$green"
sleep 2
echo -e "$blue Volviendo al menu principal"
menu_principal
;;
$d)

echo -e ¨$purple(*)$blue Seleccionaste la opcion para salir del programa.."
sleep 2
echo "adios"
exit
;;

*)
echo -e "$purple(*)$red $REPLY $blue no es una opcion valida"

;;
esac
done



